export { TelegramUI } from './telegram-ui.js';
export type { TelegramUICallbacks } from './telegram-ui.js';
export type { PeerInfo, Dialog, Message, AppState, ImageSpec, ImageSource, TelegramImageProps } from './types.js';
export { TelegramImage } from './primitives/telegram-image.js';
export { MediaCollage } from './components/media-collage.js';
export type { MediaCollageItem } from './components/media-collage.js';
export { MediaViewer } from './components/media-viewer.js';
export { TgsPlayer } from './components/tgs-player.js';
export { FpsMeter } from './components/fps-meter.js';
export { startFpsLogging } from './utils/fps-log.js';
export { setStrings, t, tpl } from './locale.js';
export { S, TLG_KEYS, LANG_FALLBACKS } from './strings.js';
export { buildPeerBlurThumb } from './utils.js';
