export const S = {
  AUTH_PHONE_LABEL: 'authPhoneLabel',
  AUTH_PHONE_PLACEHOLDER: 'authPhonePlaceholder',
  AUTH_CODE_LABEL: 'authCodeLabel',
  AUTH_CODE_PLACEHOLDER: 'authCodePlaceholder',
  AUTH_PASSWORD_LABEL: 'authPasswordLabel',
  AUTH_PASSWORD_PLACEHOLDER: 'authPasswordPlaceholder',
  AUTH_NEXT: 'authNext',
  AUTH_SIGN_IN: 'authSignIn',
  AUTH_SUBMIT: 'authSubmit',
  AUTH_RESEND_CODE: 'authResendCode',
  AUTH_APP_NAME: 'authAppName',
  AUTH_CONNECTING: 'authConnecting',
  HEADER_LOGOUT: 'headerLogout',
  SIDEBAR_DIALOGS: 'sidebarDialogs',
  SIDEBAR_LOGS: 'sidebarLogs',
  SIDEBAR_LOGS_DESC: 'sidebarLogsDesc',
  SIDEBAR_SETTINGS: 'sidebarSettings',
  SIDEBAR_SETTINGS_DESC: 'sidebarSettingsDesc',
  SETTINGS_TITLE: 'settingsTitle',
  SETTINGS_SESSION: 'settingsSession',
  SETTINGS_SESSION_ID: 'settingsSessionId',
  SETTINGS_STATUS: 'settingsStatus',
  SETTINGS_CONNECTED: 'settingsConnected',
  SETTINGS_DIALOGS_COUNT: 'settingsDialogsCount',
  SETTINGS_ACTIONS: 'settingsActions',
  SETTINGS_CLEAR_CACHE: 'settingsClearCache',
  SETTINGS_LOGOUT: 'settingsLogout',
  SETTINGS_ABOUT: 'settingsAbout',
  SETTINGS_ABOUT_TEXT: 'settingsAboutText',
  DEBUG_TITLE: 'debugTitle',
  CHAT_PLACEHOLDER: 'chatPlaceholder',
  CHAT_EMPTY: 'chatEmpty',
  CHAT_NO_MESSAGES: 'chatNoMessages',
  HISTORY_CLEARED: 'historyCleared',
  CHAT_USER_FALLBACK: 'chatUserFallback',
  STICKER_FALLBACK: 'stickerFallback',
  PHOTO_PLACEHOLDER: 'photoPlaceholder',
  YESTERDAY: 'yesterday',
  DAY_SUN: 'daySun',
  DAY_MON: 'dayMon',
  DAY_TUE: 'dayTue',
  DAY_WED: 'dayWed',
  DAY_THU: 'dayThu',
  DAY_FRI: 'dayFri',
  DAY_SAT: 'daySat',
  FILE_DEFAULT: 'fileDefault',
  AUTH_LANGUAGE: 'authLanguage',
  AUTH_COUNTRY: 'authCountry',
  LOGS_PEER: 'logsPeer',
  SETTINGS_PEER: 'settingsPeer',
  USER_FALLBACK_NAME: 'userFallbackName',
  CHAT_FALLBACK_NAME: 'chatFallbackName',
  EMOJI_TITLE: 'emojiTitle',
  SAVED_MESSAGES_PEER: 'savedMessagesPeer',

  ACTION_TYPING: 'actionTyping',
  ACTION_SENDING_PHOTO: 'actionSendingPhoto',
  ACTION_RECORDING_VIDEO: 'actionRecordingVideo',
  ACTION_SENDING_VIDEO: 'actionSendingVideo',
  ACTION_RECORDING_AUDIO: 'actionRecordingAudio',
  ACTION_SENDING_AUDIO: 'actionSendingAudio',
  ACTION_SENDING_FILE: 'actionSendingFile',
  ACTION_SENDING_LOCATION: 'actionSendingLocation',
  ACTION_CHOOSING_STICKER: 'actionChoosingSticker',
  ACTION_PLAYING_GAME: 'actionPlayingGame',
  ACTION_RECORDING_ROUND: 'actionRecordingRound',
  ACTION_SENDING_ROUND: 'actionSendingRound',

  ACTION_USER_TYPING: 'actionUserTyping',
  ACTION_USERS_TYPING: 'actionUsersTyping',
  ACTION_MANY_TYPING: 'actionManyTyping',

  SENDER_YOU: 'senderYou',
  SENDER_USER: 'senderUser',

  LOG_CODE_SENT: 'logCodeSent',
  LOG_MESSAGE_SENT: 'logMessageSent',
  LOG_CONNECTED: 'logConnected',
  LOG_HISTORY_FAILED: 'logHistoryFailed',
  LOG_HISTORY_RETRY: 'logHistoryRetry',
  LOG_HISTORY_NO_DATA: 'logHistoryNoData',
  LOG_HISTORY_NO_MSGS: 'logHistoryNoMsgs',
  LOG_UPDATE_PARSE_ERROR: 'logUpdateParseError',
  LOG_GET_DIALOGS_ERROR: 'logGetDialogsError',
  LOG_UPD_READ_OUTBOX: 'logUpdReadOutbox',
  LOG_UPD: 'logUpd',

  CONNECTION_CONNECTED: 'connectionConnected',
  CONNECTION_CONNECTING: 'connectionConnecting',
  CONNECTION_DISCONNECTED: 'connectionDisconnected',
  META_DESCRIPTION: 'metaDescription',

  API_SESSION_ID_REQUIRED: 'apiSessionIdRequired',
  API_SESSION_NOT_FOUND: 'apiSessionNotFound',
  API_PHONE_REQUIRED: 'apiPhoneRequired',
  API_SIGN_IN_REQUIRED: 'apiSignInRequired',
  API_PASSWORD_REQUIRED: 'apiPasswordRequired',
  API_PEER_REQUIRED: 'apiPeerRequired',
  API_INVALID_PEER_TYPE: 'apiInvalidPeerType',
  API_METHOD_REQUIRED: 'apiMethodRequired',
  API_DOC_OR_PHOTO_REQUIRED: 'apiDocOrPhotoRequired',
  API_NON_TEXT_MSG: 'apiNonTextMsg',
  API_UNKNOWN: 'apiUnknown',

  AUTH_SIGNUP_TITLE: 'authSignupTitle',
  AUTH_SIGNUP_DESC: 'authSignupDesc',
  AUTH_SIGNUP_FIRSTNAME: 'authSignupFirstname',
  AUTH_SIGNUP_LASTNAME: 'authSignupLastname',
  AUTH_SIGNUP_SUBMIT: 'authSignupSubmit',
  AUTH_SIGNUP_TERMS: 'authSignupTerms',
  AUTH_SIGNUP_TERMS_LINK: 'authSignupTermsLink',

  AUTH_QR_TITLE: 'authQrTitle',
  AUTH_QR_STEP1: 'authQrStep1',
  AUTH_QR_STEP2: 'authQrStep2',
  AUTH_QR_STEP3: 'authQrStep3',
  AUTH_QR_PHONE_LOGIN: 'authQrPhoneLogin',
  AUTH_QR_BUTTON: 'authQrButton',
};

export const LANG_FALLBACKS: Record<string, Record<string, string>> = {
  ru: {
    [S.SIDEBAR_SETTINGS]: 'Настройки',
    [S.SIDEBAR_LOGS]: 'События',
  },
  en: {
    [S.SIDEBAR_LOGS_DESC]: 'Connection events',
    [S.AUTH_APP_NAME]: 'Gram',
    [S.AUTH_CONNECTING]: 'Connecting...',
    [S.SIDEBAR_SETTINGS_DESC]: 'App settings',
    [S.SETTINGS_SESSION_ID]: 'Session ID',
    [S.SETTINGS_CONNECTED]: 'Connected',
    [S.SETTINGS_DIALOGS_COUNT]: 'Dialogs count',
    [S.SETTINGS_ACTIONS]: 'Actions',
    [S.SETTINGS_ABOUT_TEXT]: 'A minimal Telegram client built with GramJS',
    [S.CHAT_USER_FALLBACK]: 'User',
    [S.SENDER_YOU]: 'You',
    [S.SENDER_USER]: 'User',
    [S.LOG_CODE_SENT]: 'Code sent',
    [S.LOG_MESSAGE_SENT]: 'Message sent',
    [S.LOG_CONNECTED]: 'Connected',
    [S.LOG_HISTORY_FAILED]: 'History fetch failed',
    [S.LOG_HISTORY_RETRY]: 'Retrying history fetch',
    [S.LOG_HISTORY_NO_DATA]: 'No history data',
    [S.LOG_HISTORY_NO_MSGS]: 'No messages in history',
    [S.LOG_UPDATE_PARSE_ERROR]: 'Update parse error',
    [S.LOG_GET_DIALOGS_ERROR]: 'Get dialogs error',
    [S.LOG_UPD_READ_OUTBOX]: 'Read outbox update',
    [S.LOG_UPD]: 'Update',
    [S.CONNECTION_DISCONNECTED]: 'Disconnected',
    [S.META_DESCRIPTION]: 'A modern Telegram client',
    [S.API_SESSION_ID_REQUIRED]: 'Session ID required',
    [S.API_PHONE_REQUIRED]: 'Phone number required',
    [S.API_SIGN_IN_REQUIRED]: 'Sign in required',
    [S.API_PASSWORD_REQUIRED]: 'Password required',
    [S.API_PEER_REQUIRED]: 'Peer required',
    [S.API_INVALID_PEER_TYPE]: 'Invalid peer type',
    [S.API_METHOD_REQUIRED]: 'Method required',
    [S.API_DOC_OR_PHOTO_REQUIRED]: 'Document or photo required',
    [S.API_NON_TEXT_MSG]: 'Non-text message',
    [S.PHOTO_PLACEHOLDER]: 'Photo',
    [S.LOGS_PEER]: 'Events',
    [S.SETTINGS_PEER]: 'Settings',
    [S.USER_FALLBACK_NAME]: 'User',
    [S.CHAT_FALLBACK_NAME]: 'Chat',
  },
};

export const TLG_KEYS: Record<string, string | null> = {
  [S.AUTH_PHONE_LABEL]: 'lng_phone_number',
  [S.AUTH_PHONE_PLACEHOLDER]: 'lng_phone_ph',
  [S.AUTH_CODE_LABEL]: 'lng_code_ph',
  [S.AUTH_CODE_PLACEHOLDER]: 'lng_code_ph',
  [S.AUTH_PASSWORD_LABEL]: 'lng_signin_password',
  [S.AUTH_PASSWORD_PLACEHOLDER]: 'lng_signin_password',
  [S.AUTH_LANGUAGE]: 'lng_languages',
  [S.AUTH_COUNTRY]: 'lng_country_code',
  [S.AUTH_NEXT]: 'lng_intro_next',
  [S.AUTH_SIGN_IN]: 'lng_intro_next',
  [S.AUTH_SUBMIT]: 'lng_intro_submit',
  [S.AUTH_RESEND_CODE]: 'lng_code_no_telegram',
  [S.AUTH_APP_NAME]: null,
  [S.AUTH_CONNECTING]: 'lng_connecting',
  [S.HEADER_LOGOUT]: 'lng_settings_logout',
  [S.SAVED_MESSAGES_PEER]: 'lng_saved_messages',
  [S.SIDEBAR_DIALOGS]: 'lng_filter_chats',
  [S.SIDEBAR_LOGS]: 'lng_settings_events_title',
  [S.SIDEBAR_LOGS_DESC]: null,
  [S.SIDEBAR_SETTINGS]: 'lng_menu_settings',
  [S.SIDEBAR_SETTINGS_DESC]: null,
  [S.SETTINGS_TITLE]: 'lng_menu_settings',
  [S.SETTINGS_SESSION]: 'lng_sessions_header',
  [S.SETTINGS_SESSION_ID]: null,
  [S.SETTINGS_STATUS]: 'lng_settings_status',
  [S.SETTINGS_CONNECTED]: null,
  [S.SETTINGS_DIALOGS_COUNT]: null,
  [S.SETTINGS_ACTIONS]: null,
  [S.SETTINGS_CLEAR_CACHE]: 'lng_settings_clear_cache',
  [S.SETTINGS_LOGOUT]: 'lng_settings_logout',
  [S.SETTINGS_ABOUT]: 'lng_menu_about',
  [S.SETTINGS_ABOUT_TEXT]: null,
  [S.DEBUG_TITLE]: 'lng_log_title',
  [S.CHAT_PLACEHOLDER]: 'lng_message_ph',
  [S.CHAT_EMPTY]: 'lng_message_empty',
  [S.CHAT_NO_MESSAGES]: 'lng_chat_no_messages',
  [S.HISTORY_CLEARED]: 'lng_chat_history_cleared',
  [S.CHAT_USER_FALLBACK]: null,
  [S.YESTERDAY]: 'lng_mediaview_yesterday',
  [S.DAY_SUN]: 'lng_weekday1',
  [S.DAY_MON]: 'lng_weekday2',
  [S.DAY_TUE]: 'lng_weekday3',
  [S.DAY_WED]: 'lng_weekday4',
  [S.DAY_THU]: 'lng_weekday5',
  [S.DAY_FRI]: 'lng_weekday6',
  [S.DAY_SAT]: 'lng_weekday7',
  [S.EMOJI_TITLE]: 'lng_emoji_title',

  [S.ACTION_TYPING]: 'lng_typing',
  [S.ACTION_SENDING_PHOTO]: 'lng_send_action_upload_photo',
  [S.ACTION_RECORDING_VIDEO]: 'lng_send_action_record_video',
  [S.ACTION_SENDING_VIDEO]: 'lng_send_action_upload_video',
  [S.ACTION_RECORDING_AUDIO]: 'lng_send_action_record_audio',
  [S.ACTION_SENDING_AUDIO]: 'lng_send_action_upload_audio',
  [S.ACTION_SENDING_FILE]: 'lng_send_action_upload_file',
  [S.ACTION_SENDING_LOCATION]: 'lng_send_action_find_location',
  [S.ACTION_CHOOSING_STICKER]: 'lng_send_action_choose_sticker',
  [S.ACTION_PLAYING_GAME]: 'lng_playing_game',
  [S.ACTION_RECORDING_ROUND]: 'lng_send_action_record_round',
  [S.ACTION_SENDING_ROUND]: 'lng_send_action_upload_round',

  [S.ACTION_USER_TYPING]: 'lng_user_typing',
  [S.ACTION_USERS_TYPING]: 'lng_users_typing',
  [S.ACTION_MANY_TYPING]: 'lng_many_typing',

  [S.SENDER_YOU]: null,
  [S.SENDER_USER]: null,

  [S.LOG_CODE_SENT]: null,
  [S.LOG_MESSAGE_SENT]: null,
  [S.LOG_CONNECTED]: null,
  [S.LOG_HISTORY_FAILED]: null,
  [S.LOG_HISTORY_RETRY]: null,
  [S.LOG_HISTORY_NO_DATA]: null,
  [S.LOG_HISTORY_NO_MSGS]: null,
  [S.LOG_UPDATE_PARSE_ERROR]: null,
  [S.LOG_GET_DIALOGS_ERROR]: null,
  [S.LOG_UPD_READ_OUTBOX]: null,
  [S.LOG_UPD]: null,

  [S.CONNECTION_CONNECTED]: 'lng_connected',
  [S.CONNECTION_CONNECTING]: 'lng_connecting',
  [S.CONNECTION_DISCONNECTED]: null,
  [S.META_DESCRIPTION]: null,

  [S.AUTH_SIGNUP_TITLE]: 'lng_signup_title',
  [S.AUTH_SIGNUP_DESC]: 'lng_signup_desc',
  [S.AUTH_SIGNUP_FIRSTNAME]: 'lng_signup_firstname',
  [S.AUTH_SIGNUP_LASTNAME]: 'lng_signup_lastname',
  [S.AUTH_SIGNUP_SUBMIT]: 'lng_intro_finish',
  [S.AUTH_SIGNUP_TERMS]: 'lng_signup_terms',
  [S.AUTH_SIGNUP_TERMS_LINK]: 'lng_terms_header',

  [S.AUTH_QR_TITLE]: 'lng_intro_qr_title',
  [S.AUTH_QR_STEP1]: 'lng_intro_qr_step1',
  [S.AUTH_QR_STEP2]: 'lng_intro_qr_step2',
  [S.AUTH_QR_STEP3]: 'lng_intro_qr_step3',
  [S.AUTH_QR_PHONE_LOGIN]: 'lng_intro_qr_skip',
  [S.AUTH_QR_BUTTON]: 'lng_intro_qr_title',

  [S.API_SESSION_ID_REQUIRED]: null,
  [S.API_SESSION_NOT_FOUND]: 'lng_session_expired',
  [S.API_PHONE_REQUIRED]: null,
  [S.API_SIGN_IN_REQUIRED]: null,
  [S.API_PASSWORD_REQUIRED]: null,
  [S.API_PEER_REQUIRED]: null,
  [S.API_INVALID_PEER_TYPE]: null,
  [S.API_METHOD_REQUIRED]: null,
  [S.API_DOC_OR_PHOTO_REQUIRED]: null,
  [S.API_NON_TEXT_MSG]: null,
  [S.API_UNKNOWN]: 'lng_server_error',

  [S.STICKER_FALLBACK]: 'lng_media_sticker',
  [S.FILE_DEFAULT]: 'lng_file_default',
  [S.PHOTO_PLACEHOLDER]: null,
  [S.LOGS_PEER]: null,
  [S.SETTINGS_PEER]: null,
  [S.USER_FALLBACK_NAME]: null,
  [S.CHAT_FALLBACK_NAME]: null,
};
