import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const source = path.resolve(dir, '../gram-debug.json');
const target = path.resolve(dir, '../src/default-config.ts');

const config = JSON.parse(fs.readFileSync(source, 'utf8'));

const body = [
    '// This file is GENERATED by scripts/sync-config.mjs from gram-debug.json.',
    '// Do not edit manually — run `npm run build -w @ton-ai/gram-debug` to regenerate.',
    'import { GramDebugConfig } from \'./types\';',
    '',
    `export const defaultConfig: GramDebugConfig = ${JSON.stringify(config, null, 4)};`,
    ''
].join('\n');

fs.writeFileSync(target, body);
console.log(`[gram-debug] synced ${path.relative(path.resolve(dir, '../..'), source)} -> ${path.relative(path.resolve(dir, '../..'), target)}`);
